version: "3.7"

services:
  mariadb:
    image: mariadb:10.3
    container_name: docker-thelia-6-mariadb
    working_dir: /application
    volumes:
      - .:/application
      - .docker/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "8086:3306"

  webserver:
    image: nginx:alpine
    container_name: docker-thelia-6-webserver
    working_dir: /application
    volumes:
      - .:/application
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: .docker/php-fpm
    container_name: docker-thelia-6-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - .docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    environment:
      PHP_IDE_CONFIG: "serverName=thelia"
