name: Test

on: push

jobs:
  phpunit:
    name: PHPUnit with PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['5.6', '7.0', '7.1', '7.2', '7.3']
    container:
      image: php:${{ matrix.php_version }}-cli
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: thelia
          MYSQL_DATABASE: thelia
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@master
    - uses: php-actions/composer@v2
    - name: Install Thelia
      run: |
        php Thelia thelia:install --db_host=mysql --db_username=root --db_name=thelia --db_password=thelia
        php setup/faker.php -r 0
        php Thelia module:refresh
        php Thelia module:activate Colissimo
        php Thelia module:activate Cheque
        php Thelia module:activate HookTest
        php Thelia module:activate VirtualProductDelivery
        php Thelia admin:create --login_name thelia2 --password thelia2 --last_name thelia2 --first_name thelia2 --email thelia2@example.com
    - name: Run PHPUnit
      run: ./vendor/bin/phpunit
